steps:
        - name: 'google/cloud-sdk'
          id: 'Substitute project ID'
          entrypoint: 'bash'
          args:
                  - '-c'
                  - |
                          sed -i 's/\[PROJECT_ID\]/'\$PROJECT_ID'/g' dashboard.json

        - name: 'google/cloud-sdk'
          id: 'Delete dashboard'
          args:
                  [
                          'gcloud', 'monitoring', 'dashboards', 'delete', '--quiet', 'projects/\$PROJECT_ID/dashboards/\${_DASHBOARD_ID}''
                  ]

        - name: 'google/cloud-sdk'
          id: 'Create dashboard'
          args:
                  [
                          'gcloud', 'monitoring', 'dashboards', 'create', '--config-from-file=dashboard.json'
                  ]

